name: bilibili-test-one

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          pip install yt-dlp
          sudo apt update
          sudo apt install -y ffmpeg

      - name: write cookies
        run: |
          echo "# Netscape HTTP Cookie File" > cookies.txt
          echo ".bilibili.com TRUE / FALSE 0 SESSDATA 42448da2%2C1791886123%2C80653%2A42CjASYgzz3FLdEG9l4DJLxFq4TECOCGWdFYLDheY0cV53lN7u36G5299i0Zht32cRe3MSVkE5dnhGTUJwUTJacXBMMW5yYnc4LW8tNWQ5bTQ1dVIzdDJIQ0psLWV4OVJqNlJkNHVDSEVfUTlmZTYyVXRPUzk3eU1WMlRLb0dSaFZ2UllUbC1Bbk13IIEC" >> cookies.txt

      - name: download
        run: |
          yt-dlp "https://www.bilibili.com/video/BV187Msz4Ebg" \
          -f bestaudio \
          --extract-audio \
          --audio-format mp3 \
          --write-subs \
          --write-auto-subs \
          --convert-subs srt \
          --cookies cookies.txt

      - name: make video
        run: |
          for f in *.mp3; do
            echo "Making video for $f"
            sub=$(ls "${f%.mp3}".*.srt 2>/dev/null | head -n 1)
            if [ -f "$sub" ]; then
              ffmpeg -f lavfi -i color=c=black:s=1280x720 \
              -i "$f" -shortest \
              -vf "subtitles=$sub:force_style='Fontsize=36,Alignment=10,Outline=3'" \
              -c:v libx264 -c:a aac -b:a 192k \
              "${f%.mp3}.mp4"
            else
              echo "No subtitle found"
            fi
          done

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: result-one
          path: |
            *.mp4
            *.mp3
            *.srt
